import { BUSINESS } from './business';
import { PROCESSORS } from './processors';
import type { LegalDoc } from './types';

/**
 * Every table or store that holds personal data, in the words the notice uses for it.
 * `legal.test.ts` checks each phrase appears in the notice. When a new table starts holding
 * personal data, add it here in the same change — the old notice's rule, now enforced.
 */
export const PERSONAL_DATA_STORES = [
  'auth.users',
  'profiles',
  'question_attempts',
  'cohort_members',
  'licence_seats',
  'chat_usage',
  'reviews',
  'billing_events',
] as const;

export const PRIVACY: LegalDoc = {
  id: 'privacy',
  title: 'Privacy policy',
  summary: 'What we collect, why, who else sees it, how long we keep it, and your rights.',
  lastUpdated: '2026-09-28',
  sections: [
    {
      heading: 'Who we are',
      paragraphs: [
        `${BUSINESS.productName} is run by ${BUSINESS.legalName}, trading as ${BUSINESS.tradingName} ("we"). We are the controller of your personal data under the UK GDPR and the Data Protection Act 2018.`,
        `Address: ${BUSINESS.address}. Privacy questions: ${BUSINESS.privacyEmail}. ICO registration: ${BUSINESS.icoRegistration}.`,
        'The service is for adults: you must be 18 or over to create an account.',
      ],
    },
    {
      heading: 'If you use the app without an account',
      paragraphs: [
        'Your progress lives only on your device (browser local storage, or the phone app\'s own storage). Nothing about it is sent to us, and clearing your browser or app data erases it completely.',
        'On the website, Google Analytics runs only if you accept analytics cookies. See the cookie policy.',
      ],
      links: [{ label: 'Cookie policy', route: 'cookies' }],
    },
    {
      heading: 'If you create an account',
      paragraphs: ['We store:'],
      list: [
        'Your email address and a password hash — we can never read the password itself (auth.users). Also the version of the Terms you accepted and when.',
        'Your profile (profiles): subscription status and renewal date, your role (learner or teacher), and — only if you choose them — your target exam and training stage.',
        'Each practice question you answer: which module, which question, right or wrong, and when (question_attempts).',
        'Classes you join and institutional licence seats you redeem (cohort_members, licence_seats).',
        'A timestamp each time you send the AI tutor a message, so we can apply the daily limit (chat_usage). The message itself is not stored.',
        'A review, if you write one (reviews): your rating, your text and the optional display name you give.',
        'Records of subscription payments and invoices, sent to us by RevenueCat and Stripe (billing_events).',
      ],
    },
    {
      heading: 'The AI tutor',
      paragraphs: [
        'When you ask the tutor a question, we send it to an AI model provider (Mistral AI first, Google\'s Gemini API as a backup) together with: your recent messages in that conversation, excerpts from our own teaching material, the name of the module you are on, the readings currently on screen, and a short summary of up to five topics you find difficult (for example "Shock states: 3 due for review, mastery 40%").',
        'We do not send your name, email address or account ID. Answers are generated by AI and can be wrong; do not rely on them for clinical decisions.',
        'Please do not type personal information about yourself or anyone else — especially patient information — into the tutor.',
      ],
    },
    {
      heading: 'Why we use your data, and our legal basis',
      list: [
        'To provide the service you signed up for — your account, progress syncing between devices, bringing back questions you got wrong, the tutor, and your subscription. Legal basis: contract.',
        'To let a teacher see how their class is doing, if you join a class or your school buys you a licence. Legal basis: contract (with you or with your institution) and our legitimate interest in supporting institutional teaching.',
        'To keep payment and tax records. Legal basis: legal obligation.',
        'To prevent abuse, such as enforcing the tutor\'s daily limit. Legal basis: legitimate interests.',
        'To publish your review, if you submit one. Legal basis: consent, which you can withdraw by deleting the review.',
        'To count website visits with Google Analytics. Legal basis: consent, given through the cookie banner and withdrawable at any time.',
      ],
      closing: ['We do not sell your data, show advertising, or make decisions about you by automated means that have legal or similarly significant effects.'],
    },
    {
      heading: 'If you join a class',
      paragraphs: [
        'Joining a class with a code — or being enrolled in one by a licence your school bought — lets the teacher who runs it see how that class is getting on. Their dashboard shows the class as a whole: how many people have attempted each module and what proportion were correct. It does not list students, and a module is left blank until at least five people have attempted it, so a class average cannot be read back as one person\'s result.',
        'Being straight about the limit of that: the database permission your teacher holds covers the answers of people in their own classes, and it is what makes the class figures possible. Nobody else can see them, no other teacher can, and leaving the class ends it.',
      ],
    },
    {
      heading: 'Who else receives your data',
      paragraphs: [
        'We use these service providers. Each processes data only to provide its service to us (Apple and Google act as independent controllers for store purchases). Where data leaves the UK, the safeguard is listed.',
      ],
      table: {
        head: ['Provider', 'What for', 'What data', 'Where', 'Safeguard'],
        rows: PROCESSORS.map((p) => [p.name, p.role, p.data, p.location, p.transferBasis]),
      },
    },
    {
      heading: 'How long we keep it',
      list: [
        'Account, profile, answers, classes and reviews: until you delete your account, then removed immediately.',
        'Tutor usage timestamps: 90 days.',
        'Payment and invoice records: 6 years after the end of the tax year they relate to, as HMRC requires. When you delete your account we remove the detailed payment payload and keep only the minimum record.',
        'Google Analytics data: 14 months.',
      ],
    },
    {
      heading: 'Deleting your account',
      paragraphs: [
        'Delete your account from the account page (website) or the Account tab (phone app). It removes your email address, every recorded answer, your classes, your review and your access rights from our servers immediately. You do not need to ask.',
        'Deleting your account does not cancel an App Store or Google Play subscription — cancel that in your store settings first. Apple, Google, RevenueCat and Stripe keep their own purchase records under their own policies.',
      ],
      links: [{ label: 'Go to your account', route: 'account' }],
    },
    {
      heading: 'Your rights',
      paragraphs: ['Under UK data protection law you have the right to:'],
      list: [
        'access a copy of your data',
        'have inaccurate data corrected',
        'have your data deleted',
        'restrict or object to how we use it',
        'receive your data in a portable format',
        'withdraw consent at any time, where we rely on consent',
      ],
    },
    {
      heading: 'Contact and complaints',
      paragraphs: [
        `Email ${BUSINESS.privacyEmail} to use any of these rights or ask a question. We reply within one month.`,
        'If you are unhappy with how we have handled your data, you can complain to the Information Commissioner\'s Office (ICO): ico.org.uk/make-a-complaint or 0303 123 1113. We would appreciate the chance to put it right first.',
      ],
      links: [
        { label: `Email ${BUSINESS.privacyEmail}`, href: `mailto:${BUSINESS.privacyEmail}` },
        { label: 'ICO: make a complaint', href: 'https://ico.org.uk/make-a-complaint/' },
      ],
    },
    {
      heading: 'Changes to this policy',
      paragraphs: [
        'If we change what we collect or who receives it, we will update this page and its date. If the change is significant we will tell you by email or in the app before it takes effect.',
      ],
    },
  ],
};
