import { BUSINESS } from './business';
import type { LegalDoc } from './types';

/**
 * The contract. Written to be read, and to leave every statutory consumer right intact —
 * under the Consumer Rights Act 2015 s.31 and s.65 a term that tries to exclude them is simply
 * not binding, and saying otherwise is itself an unfair practice. Have a solicitor review before
 * launch; see the checklist in docs/compliance/UK-COMPLIANCE.md.
 */
export const TERMS: LegalDoc = {
  id: 'terms',
  title: 'Terms and conditions',
  summary: 'The agreement between you and us when you use Physiology Lab.',
  lastUpdated: '2026-09-28',
  sections: [
    {
      heading: '1. Who we are',
      paragraphs: [
        `${BUSINESS.productName} (the website and the phone app, together "the service") is provided by ${BUSINESS.legalName}, trading as ${BUSINESS.tradingName}, ${BUSINESS.address}. Company number: ${BUSINESS.companyNumber}. VAT: ${BUSINESS.vatNumber}.`,
        `Contact us at ${BUSINESS.contactEmail}.`,
      ],
      links: [{ label: 'Business details', route: 'business' }],
    },
    {
      heading: '2. Who can use the service',
      paragraphs: [
        'You must be 18 or over to create an account. By creating one you confirm that you are, and that the details you give are accurate.',
        'Keep your password to yourself. An account is for one person; sharing it is not allowed.',
      ],
    },
    {
      heading: '3. What the service is — and is not',
      paragraphs: [
        'The service is an educational tool. Its simulators are simplified, conceptual models built to teach physiological mechanism. They are not clinical or diagnostic tools, not a medical device, and must never be used to make decisions about the care of a real patient.',
        'Drug information in the app describes mechanisms for learning purposes. It is not prescribing guidance; always use the BNF, local guidelines and senior advice in practice.',
        'We work hard to make the content accurate and we explain how the physiology is checked, but we do not promise that it is free of errors or that using it will lead to any particular exam result.',
      ],
      links: [{ label: 'How the physiology is checked', route: 'methodology' }],
    },
    {
      heading: '4. The AI tutor',
      paragraphs: [
        'The tutor\'s answers are generated by a third-party AI model. They can be incomplete or wrong, and are clearly marked as AI-generated. Check anything important against a reliable source.',
        'Do not enter information that identifies a patient or any other person. There is a daily message limit so that the service stays available to everyone.',
      ],
    },
    {
      heading: '5. Exams and trade marks',
      paragraphs: [
        'We tag content by exam to help you find it. We are not affiliated with, endorsed by or sponsored by any exam body. USMLE is a program of the Federation of State Medical Boards (FSMB) and the National Board of Medical Examiners (NBME). MRCS is examined by the surgical Royal Colleges of the UK and Ireland. The Primary FRCA is an examination of the Royal College of Anaesthetists. MRCP(UK) is an examination of the Federation of the Royal Colleges of Physicians of the UK. The UKMLA is run by the General Medical Council. All names are the property of their owners.',
      ],
    },
    {
      heading: '6. Free and paid access',
      paragraphs: [
        'Some simulators are free with any account. Full access is available by personal subscription or through a licence bought by your institution.',
        'Personal subscriptions are monthly or annual. The price, the billing period and what is included are shown before you pay. Prices include VAT where it applies.',
        'Your subscription renews automatically at the end of each period, at the price then in force, until you cancel. If the price is going to change we will tell you at least 30 days before your next renewal, and you can cancel before it takes effect.',
      ],
      links: [{ label: 'Plans and prices', route: 'pricing' }],
    },
    {
      heading: '7. Cancelling',
      list: [
        'Website subscriptions: cancel at any time from your account page ("Manage or cancel your subscription") or by emailing us. You keep access until the end of the period you have paid for, and you are not charged again.',
        'App Store or Google Play subscriptions: cancel in your device\'s subscription settings. Apple or Google handle billing and refunds for these.',
        'You also have a legal right to cancel within 14 days of first subscribing. See the refund policy for how this works and what you get back.',
      ],
      links: [{ label: 'Refund policy', route: 'refunds' }],
    },
    {
      heading: '8. Institutional licences',
      paragraphs: [
        'If your institution gives you a licence code, your access lasts for the term your institution bought and is governed by our agreement with them. Redeeming a code may add you to a class; see the privacy policy for what your teacher can see.',
      ],
    },
    {
      heading: '9. Using the service fairly',
      paragraphs: ['You agree not to:'],
      list: [
        'copy, resell or redistribute the content, questions or simulators',
        'scrape the service, or try to get around access controls, rate limits or the paywall',
        'interfere with the service or other people\'s use of it',
        'post reviews that are false, not your own genuine experience, or written in return for payment or a reward',
      ],
    },
    {
      heading: '10. Reviews',
      paragraphs: [
        'You can review the service once per account. Reviews are checked before they appear. We publish genuine reviews whether they are positive or negative, and only reject a review that is abusive, spam, off-topic, includes personal information or is not about your own experience. We never pay for or incentivise reviews.',
      ],
      links: [{ label: 'Read and write reviews', route: 'reviews' }],
    },
    {
      heading: '11. Intellectual property',
      paragraphs: [
        'We (or our licensors) own the content of the service. We give you a personal, non-transferable right to use it for your own learning while your account is active. This does not affect any open-source licences that apply to parts of the software.',
      ],
    },
    {
      heading: '12. Our responsibility to you',
      paragraphs: [
        'If you are a consumer, you have legal rights under the Consumer Rights Act 2015: digital content must be of satisfactory quality, fit for purpose and as described, and services must be provided with reasonable care and skill. Nothing in these terms affects those rights. If something we supply is faulty, tell us and we will repair or replace it, or give you some or all of your money back.',
        'We are responsible for loss or damage you suffer that is a foreseeable result of our breaking these terms or failing to use reasonable care. We are not responsible for loss that was not foreseeable, for business losses, or for decisions made by relying on the service against the warning in section 3.',
        'Nothing in these terms limits our liability for death or personal injury caused by our negligence, for fraud, or for anything else that cannot be limited by law.',
      ],
    },
    {
      heading: '13. Suspending or ending your account',
      paragraphs: [
        'You can delete your account at any time. We may suspend or close an account that seriously or repeatedly breaks these terms; we will tell you why and, if you have paid for a period you will not receive, refund the unused part unless the breach was deliberate.',
        'We may need to change or withdraw features. If a change significantly reduces what a paid subscription gives you, you may cancel and receive a pro-rata refund.',
      ],
    },
    {
      heading: '14. Changes to these terms',
      paragraphs: [
        'We may update these terms. We will give you at least 30 days\' notice of a significant change, by email or in the app. If you do not agree, you can cancel before the change takes effect.',
      ],
    },
    {
      heading: '15. Complaints and the law',
      paragraphs: [
        `Please contact ${BUSINESS.contactEmail} first; we aim to reply within 5 working days.`,
        `These terms are governed by the law of ${BUSINESS.governingLaw}. If you are a consumer living elsewhere in the UK, you can bring proceedings in your local courts and keep the protection of your local law.`,
      ],
    },
  ],
};
