import { ELASTANCE } from './constants';
import { clamp } from '../math';

/**
 * Time-varying elastance E(t), the Suga-Sagawa description of ventricular mechanics: rather
 * than modeling muscle directly, treat the ventricle as a chamber whose stiffness rises
 * through systole and falls through diastole. Pressure at any instant is then simply
 * E(t) × (V − V0).
 *
 * This one idea generates the whole pressure-volume loop: contractility scales the peak
 * (end-systolic) elastance, which is exactly why increased contractility shifts the ESPVR line
 * upward and to the left, ejecting more blood from the same end-diastolic volume.
 */
export function elastanceAtPhase(cyclePhaseFraction: number, contractility: number): number {
  const endSystolicElastance = ELASTANCE.END_SYSTOLIC_ELASTANCE * clamp(contractility, 0, 2);

  if (cyclePhaseFraction > ELASTANCE.SYSTOLE_FRACTION) {
    return ELASTANCE.END_DIASTOLIC_ELASTANCE;
  }

  // A smooth rise-and-fall across systole, peaking at PEAK_ELASTANCE_PHASE.
  const systolicProgress = cyclePhaseFraction / ELASTANCE.SYSTOLE_FRACTION;
  const shape = Math.sin(Math.PI * Math.min(systolicProgress / ELASTANCE.PEAK_ELASTANCE_PHASE, 1) * 0.5) ** 2;
  const decay = systolicProgress > ELASTANCE.PEAK_ELASTANCE_PHASE
    ? Math.cos((Math.PI / 2) * ((systolicProgress - ELASTANCE.PEAK_ELASTANCE_PHASE) / (1 - ELASTANCE.PEAK_ELASTANCE_PHASE))) ** 2
    : 1;

  return ELASTANCE.END_DIASTOLIC_ELASTANCE + (endSystolicElastance - ELASTANCE.END_DIASTOLIC_ELASTANCE) * shape * decay;
}

/** Pressure generated by the chamber at a given volume and elastance: P = E × (V − V0). */
export function chamberPressure(volumeML: number, elastance: number): number {
  return Math.max(0, elastance * (volumeML - ELASTANCE.UNSTRESSED_VOLUME_ML));
}
