import type { ExplainerContent } from '../../shared/explainer/types';
import type { NmjPresetName } from './presets';

export const neuromuscularJunctionContent: ExplainerContent<NmjPresetName> = {
  title: 'A reserve so large that losing it is invisible until it is gone',
  sections: [
    {
      heading: 'Transmission here is deliberately over-engineered',
      paragraphs: [
        'Transmission at the neuromuscular junction is deliberately over-engineered. A normal impulse releases far more acetylcholine than is needed, so the end-plate potential overshoots the threshold for firing the muscle fibre by roughly fourfold. That margin is the safety factor, and it is the single most useful idea here: it means transmission is not graded but all-or-none at each junction, and it means losing half the receptors changes nothing a patient would notice. Weakness appears only once the reserve is genuinely spent — and then it appears quickly.',
      ],
      demos: [
        { preset: 'normal', watch: 'safety factor' },
      ],
    },
    {
      heading: 'Graded weakness is the fraction of junctions failing',
      paragraphs: [
        'Because each junction is all-or-none, the graded weakness a patient shows is not each junction working less well. It is the fraction of junctions failing. Drag the receptor density down and watch force stay at 100% for a long while before it falls away steeply. That plateau followed by a cliff is why myasthenia can present abruptly in someone who has been losing receptors for months.',
      ],
      demos: [
        { preset: 'myastheniaGravis', watch: 'force' },
      ],
    },
    {
      heading: 'To find a junction with no reserve, make it work repeatedly',
      paragraphs: [
        'The way to find a junction with no reserve left is to make it work repeatedly. A train of four stimuli draws down the immediately available store of vesicles faster than the terminal can mobilise more, so each successive response is generated by slightly less transmitter. In a healthy junction that does not matter — a fourfold reserve absorbs it and all four responses are identical. Take the reserve away and the same depletion now crosses threshold, so the later responses fail. Fade is not a new phenomenon in disease; it is normal depletion made visible by a lost margin.',
      ],
    },
    {
      heading: 'Repetition does opposite things to the two lesions',
      paragraphs: [
        'Two very different lesions produce weakness, and repetition tells them apart because it does opposite things to each. Myasthenia gravis is postsynaptic: antibodies destroy receptors, the nerve releases normally, and repetition makes matters worse. Lambert-Eaton is presynaptic: antibodies attack the calcium channels that trigger release, so too little is released to begin with — but calcium accumulates in the terminal during rapid firing, and release goes as a steep power of calcium. Stimulate fast enough and a Lambert-Eaton junction improves several-fold. The patient is briefly stronger after exercising, which is the exact reverse of myasthenic fatiguability.',
      ],
      demos: [
        { preset: 'lambertEaton', watch: 'train of four' },
        { preset: 'botulism', watch: 'force' },
      ],
    },
    {
      heading: 'The two relaxant classes separate on the same test',
      paragraphs: [
        'The two classes of muscle relaxant separate on the same test, and for a related reason. A competitive antagonist occupies postsynaptic receptors and presynaptic autoreceptors, and those autoreceptors are what normally mobilise extra vesicles during a train — so a non-depolarising block fades. A depolarising agonist opens the receptor and holds it there; it does not touch the autoreceptor, so its block does not fade in the same way. That difference is what a peripheral nerve stimulator is reading, and it is why an anticholinesterase reverses one and deepens the other.',
      ],
      demos: [
        { preset: 'nondepolarisingBlock', watch: 'train of four' },
        { preset: 'depolarisingBlock', watch: 'train of four' },
      ],
    },
    {
      heading: 'Driving the surviving receptors harder has a ceiling',
      paragraphs: [
        'Which brings you to the last idea, which catches people out. Blocking acetylcholinesterase makes each quantum larger and longer-lived, so it treats myasthenia by driving the surviving receptors harder. Take it far enough — an organophosphate rather than a therapeutic dose — and transmitter accumulates until the end plate sits persistently depolarised and simply stops responding. Too much agonist produces a block of exactly the same kind as the agonist drug does. Fasciculation first, then paralysis, and giving more anticholinesterase makes it worse.',
      ],
      demos: [
        { preset: 'pyridostigmine', watch: 'force' },
        { preset: 'organophosphate', watch: 'force' },
      ],
    },
  ],
};
